name: Download Android SDK Parts

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Download Android commandline tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip
          mkdir -p android-sdk/cmdline-tools/latest
          mv cmdline-tools/* android-sdk/cmdline-tools/latest/

      - name: Install SDK packages
        run: |
          export ANDROID_SDK_ROOT=$PWD/android-sdk
          yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-36" \
            "build-tools;28.0.3"

      - name: Zip SDK
        run: |
          zip -r android-sdk.zip android-sdk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-sdk
          path: android-sdk.zip
