name: Download JDK 17

on:
  workflow_dispatch:

jobs:
  download-jdk:
    runs-on: windows-latest

    steps:
      - name: Download JDK 17
        run: |
          mkdir C:\jdk
          curl -L "https://github.com/adoptium/temurin17-binaries/releases/latest/download/OpenJDK17U-jdk_x64_windows_hotspot.zip" -o C:\jdk\jdk17.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jdk17
          path: C:\jdk\jdk17.zip
